// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOARvZbdnBMJo--jRrVeHOsTbofYmPzQ',
    appId: '1:517360489384:web:8a36a7a27f327e55b7839d',
    messagingSenderId: '517360489384',
    projectId: 'el-moza3-52945',
    authDomain: 'el-moza3-52945.firebaseapp.com',
    storageBucket: 'el-moza3-52945.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB44N9w1ACclW2FwaERDo1O9y6FNLxETOg',
    appId: '1:517360489384:android:69cb82ac82b6c86eb7839d',
    messagingSenderId: '517360489384',
    projectId: 'el-moza3-52945',
    storageBucket: 'el-moza3-52945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATF7XR9uxX1xcbQa_AuZE98x90SaTfbyQ',
    appId: '1:517360489384:ios:c0ecab9ef794be42b7839d',
    messagingSenderId: '517360489384',
    projectId: 'el-moza3-52945',
    storageBucket: 'el-moza3-52945.firebasestorage.app',
    iosClientId:
        '517360489384-7b35roeda2cfqh6htaip38fes4ok7np6.apps.googleusercontent.com',
    iosBundleId: 'com.example.elMoza3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATF7XR9uxX1xcbQa_AuZE98x90SaTfbyQ',
    appId: '1:517360489384:ios:c0ecab9ef794be42b7839d',
    messagingSenderId: '517360489384',
    projectId: 'el-moza3-52945',
    storageBucket: 'el-moza3-52945.firebasestorage.app',
    iosClientId:
        '517360489384-7b35roeda2cfqh6htaip38fes4ok7np6.apps.googleusercontent.com',
    iosBundleId: 'com.example.elMoza3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVOARvZbdnBMJo--jRrVeHOsTbofYmPzQ',
    appId: '1:517360489384:web:afeaad09b4c54b64b7839d',
    messagingSenderId: '517360489384',
    projectId: 'el-moza3-52945',
    authDomain: 'el-moza3-52945.firebaseapp.com',
    storageBucket: 'el-moza3-52945.firebasestorage.app',
  );
}
